### ISSUE TITLE
How to run it ?

### ISSUE THREAD

**Issue by aligos** [ryanswapp/meteor-redux-todos-react#1]
Please give me know, how to run this meteor redux todos react

**Comment by ryanswapp** [comment]
I don't think I ever got around to making this work. Redux doesn't fit too well into the Meteor way of doing things. It's more appropriate for a typical client/server app like a Rails/PHP backend with a React/Angular/Ember frontend where you need a way to manage state on the frontend. This isn't a repo you should pay any attention to as it's incomplete and isn't the best way of doing things.
